# fly.toml app configuration file generated for lead-scraper-engine on 2026-05-05T08:03:32Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'lead-scraper-engine'
primary_region = 'ams'

[build]

[[vm]]
  memory = '1gb'
  cpus = 1
  memory_mb = 1024
